//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuzzleSolvers.Nonogram.Tests {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TestFilesXML {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestFilesXML() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PuzzleSolvers.Nonogram.Tests.TestFilesXML", typeof(TestFilesXML).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE pbn SYSTEM &quot;https://webpbn.com/pbn-0.3.dtd&quot;&gt;
        ///&lt;puzzleset&gt;
        ///&lt;source&gt;webpbn.com&lt;/source&gt;
        ///
        ///&lt;puzzle type=&quot;grid&quot; defaultcolor=&quot;black&quot;&gt;
        ///&lt;title&gt;Demo Puzzle from Front Page&lt;/title&gt;
        ///&lt;author&gt;Jan Wolter&lt;/author&gt;
        ///&lt;authorid&gt;jan&lt;/authorid&gt;
        ///&lt;copyright&gt;(c) Copyright 2004 by Jan Wolter&lt;/copyright&gt;
        ///&lt;id&gt;#1 (v.1)&lt;/id&gt;
        ///&lt;description&gt;A stick figure man, dancing his stickly little heart out.&lt;/description&gt;
        ///&lt;note&gt;published,definitely unique,definitely line/color solvable&lt;/note&gt;
        ///
        ///&lt;color name=&quot;white&quot; char [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string webpbn000001 {
            get {
                return ResourceManager.GetString("webpbn000001", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE pbn SYSTEM &quot;https://webpbn.com/pbn-0.3.dtd&quot;&gt;
        ///&lt;puzzleset&gt;
        ///&lt;source&gt;webpbn.com&lt;/source&gt;
        ///
        ///&lt;puzzle type=&quot;grid&quot; defaultcolor=&quot;black&quot;&gt;
        ///&lt;title&gt;Scardy Cat&lt;/title&gt;
        ///&lt;author&gt;Jan Wolter&lt;/author&gt;
        ///&lt;authorid&gt;jan&lt;/authorid&gt;
        ///&lt;copyright&gt;(c) Copyright 2004 by Jan Wolter&lt;/copyright&gt;
        ///&lt;id&gt;#6 (v.1)&lt;/id&gt;
        ///&lt;description&gt;A frightened cat&lt;/description&gt;
        ///&lt;note&gt;published,definitely unique,definitely line/color solvable&lt;/note&gt;
        ///
        ///&lt;color name=&quot;white&quot; char=&quot;.&quot;&gt;FFFFFF&lt;/color&gt;
        ///&lt;color name=&quot;black&quot; char=&quot;X&quot;&gt;000000&lt;/c [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string webpbn000006 {
            get {
                return ResourceManager.GetString("webpbn000006", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE pbn SYSTEM &quot;https://webpbn.com/pbn-0.3.dtd&quot;&gt;
        ///&lt;puzzleset&gt;
        ///&lt;source&gt;webpbn.com&lt;/source&gt;
        ///
        ///&lt;puzzle type=&quot;grid&quot; defaultcolor=&quot;black&quot;&gt;
        ///&lt;title&gt;Probably Not&lt;/title&gt;
        ///&lt;author&gt;Jan Wolter&lt;/author&gt;
        ///&lt;authorid&gt;jan&lt;/authorid&gt;
        ///&lt;copyright&gt;(c) Copyright 2004 by Jan Wolter&lt;/copyright&gt;
        ///&lt;id&gt;#16 (v.1)&lt;/id&gt;
        ///&lt;description&gt;A classic two loop Celtic Knot design.&lt;/description&gt;
        ///&lt;note&gt;published,definitely unique,definitely line/color solvable&lt;/note&gt;
        ///
        ///&lt;color name=&quot;white&quot; char=&quot;.&quot;&gt;FFFFFF&lt;/color&gt;
        ///&lt;color name=&quot; [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string webpbn000016 {
            get {
                return ResourceManager.GetString("webpbn000016", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE pbn SYSTEM &quot;https://webpbn.com/pbn-0.3.dtd&quot;&gt;
        ///&lt;puzzleset&gt;
        ///&lt;source&gt;webpbn.com&lt;/source&gt;
        ///
        ///&lt;puzzle type=&quot;grid&quot; defaultcolor=&quot;black&quot;&gt;
        ///&lt;title&gt;Slippery Conditions&lt;/title&gt;
        ///&lt;author&gt;Jan Wolter&lt;/author&gt;
        ///&lt;authorid&gt;jan&lt;/authorid&gt;
        ///&lt;copyright&gt;(c) Copyright 2004 by Jan Wolter&lt;/copyright&gt;
        ///&lt;id&gt;#21 (v.1)&lt;/id&gt;
        ///&lt;description&gt;Icon from &amp;quot;Slippery when Wet&amp;quot; warning sign.  My first versions had more dramatic skid marks, but weren&amp;apos;t solvable.&lt;/description&gt;
        ///&lt;note&gt;published,definitely uniqu [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string webpbn000021 {
            get {
                return ResourceManager.GetString("webpbn000021", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE pbn SYSTEM &quot;https://webpbn.com/pbn-0.3.dtd&quot;&gt;
        ///&lt;puzzleset&gt;
        ///&lt;source&gt;webpbn.com&lt;/source&gt;
        ///
        ///&lt;puzzle type=&quot;grid&quot; defaultcolor=&quot;black&quot;&gt;
        ///&lt;title&gt;Nonrepresentational Test Pattern&lt;/title&gt;
        ///&lt;author&gt;Jan Wolter&lt;/author&gt;
        ///&lt;authorid&gt;jan&lt;/authorid&gt;
        ///&lt;copyright&gt;(c) Copyright 2004 by Jan Wolter&lt;/copyright&gt;
        ///&lt;id&gt;#23 (v.1)&lt;/id&gt;
        ///&lt;description&gt;Two hats falling from a cloud?  No, just simple example of the usefulness of edges.&lt;/description&gt;
        ///&lt;note&gt;published,definitely unique,definitely requires moderate lo [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string webpbn000023 {
            get {
                return ResourceManager.GetString("webpbn000023", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE pbn SYSTEM &quot;https://webpbn.com/pbn-0.3.dtd&quot;&gt;
        ///&lt;puzzleset&gt;
        ///&lt;source&gt;webpbn.com&lt;/source&gt;
        ///
        ///&lt;puzzle type=&quot;grid&quot; defaultcolor=&quot;black&quot;&gt;
        ///&lt;title&gt;Party at the Right [Political]&lt;/title&gt;
        ///&lt;author&gt;Jan Wolter&lt;/author&gt;
        ///&lt;authorid&gt;jan&lt;/authorid&gt;
        ///&lt;copyright&gt;(c) Copyright 2004 by Jan Wolter&lt;/copyright&gt;
        ///&lt;id&gt;#27 (v.1)&lt;/id&gt;
        ///&lt;description&gt;Republican Party Symbol, almost.  Top half should be blue and bottom half red.  Also stars are too hard to draw.&lt;/description&gt;
        ///&lt;note&gt;published,definitely unique,defi [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string webpbn000027 {
            get {
                return ResourceManager.GetString("webpbn000027", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE pbn SYSTEM &quot;https://webpbn.com/pbn-0.3.dtd&quot;&gt;
        ///&lt;puzzleset&gt;
        ///&lt;source&gt;webpbn.com&lt;/source&gt;
        ///
        ///&lt;puzzle type=&quot;grid&quot; defaultcolor=&quot;black&quot;&gt;
        ///&lt;title&gt;Mum&amp;apos;s the Word [has only one solution]&lt;/title&gt;
        ///&lt;author&gt;Jan Wolter&lt;/author&gt;
        ///&lt;authorid&gt;jan&lt;/authorid&gt;
        ///&lt;copyright&gt;(c) Copyright 2004 by Jan Wolter&lt;/copyright&gt;
        ///&lt;id&gt;#65 (v.1)&lt;/id&gt;
        ///&lt;description&gt;Death mask for King Tutankhaten&amp;apos;s Mummy.&lt;/description&gt;
        ///&lt;note&gt;published,definitely unique,definitely requires moderate lookahead&lt;/note&gt;
        ///
        ///&lt;color name [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string webpbn000065 {
            get {
                return ResourceManager.GetString("webpbn000065", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE pbn SYSTEM &quot;https://webpbn.com/pbn-0.3.dtd&quot;&gt;
        ///&lt;puzzleset&gt;
        ///&lt;source&gt;webpbn.com&lt;/source&gt;
        ///
        ///&lt;puzzle type=&quot;grid&quot; defaultcolor=&quot;black&quot;&gt;
        ///&lt;title&gt;Old Stone Face&lt;/title&gt;
        ///&lt;author&gt;Jan Wolter&lt;/author&gt;
        ///&lt;authorid&gt;jan&lt;/authorid&gt;
        ///&lt;copyright&gt;(c) Copyright 2006 by Jan Wolter&lt;/copyright&gt;
        ///&lt;id&gt;#436 (v.1)&lt;/id&gt;
        ///&lt;description&gt;A petroglyph from British Columbia.&lt;/description&gt;
        ///&lt;note&gt;published,definitely unique,definitely requires moderate lookahead&lt;/note&gt;
        ///
        ///&lt;color name=&quot;white&quot; char=&quot;.&quot;&gt;FFFFFF&lt;/color&gt;
        ///&lt;colo [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string webpbn000436 {
            get {
                return ResourceManager.GetString("webpbn000436", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE pbn SYSTEM &quot;https://webpbn.com/pbn-0.3.dtd&quot;&gt;
        ///&lt;puzzleset&gt;
        ///&lt;source&gt;webpbn.com&lt;/source&gt;
        ///
        ///&lt;puzzle type=&quot;grid&quot; defaultcolor=&quot;black&quot;&gt;
        ///&lt;title&gt;Swing&lt;/title&gt;
        ///&lt;author&gt;Jan Wolter&lt;/author&gt;
        ///&lt;authorid&gt;jan&lt;/authorid&gt;
        ///&lt;copyright&gt;(c) Copyright 2006 by Jan Wolter&lt;/copyright&gt;
        ///&lt;id&gt;#529 (v.1)&lt;/id&gt;
        ///&lt;description&gt;A couple of merry dancers.&lt;/description&gt;
        ///&lt;note&gt;published,definitely unique,definitely line/color solvable&lt;/note&gt;
        ///
        ///&lt;color name=&quot;white&quot; char=&quot;.&quot;&gt;FFFFFF&lt;/color&gt;
        ///&lt;color name=&quot;black&quot; char=&quot;X&quot;&gt;00 [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string webpbn000529 {
            get {
                return ResourceManager.GetString("webpbn000529", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE pbn SYSTEM &quot;https://webpbn.com/pbn-0.3.dtd&quot;&gt;
        ///&lt;puzzleset&gt;
        ///&lt;source&gt;webpbn.com&lt;/source&gt;
        ///
        ///&lt;puzzle type=&quot;grid&quot; defaultcolor=&quot;black&quot;&gt;
        ///&lt;title&gt;You light up my life&lt;/title&gt;
        ///&lt;author&gt;Robert Kummerfeldt&lt;/author&gt;
        ///&lt;authorid&gt;rmkummerfeldt&lt;/authorid&gt;
        ///&lt;copyright&gt;(c) Copyright 2007 by Robert Kummerfeldt&lt;/copyright&gt;
        ///&lt;id&gt;#803 (v.1)&lt;/id&gt;
        ///&lt;description&gt;Lighthouse very roughly based on the March picture in my 2007 calendar&lt;/description&gt;
        ///&lt;note&gt;published,definitely unique,definitely requires moderate  [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string webpbn000803 {
            get {
                return ResourceManager.GetString("webpbn000803", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE pbn SYSTEM &quot;https://webpbn.com/pbn-0.3.dtd&quot;&gt;
        ///&lt;puzzleset&gt;
        ///&lt;source&gt;webpbn.com&lt;/source&gt;
        ///
        ///&lt;puzzle type=&quot;grid&quot; defaultcolor=&quot;black&quot;&gt;
        ///&lt;title&gt;For  merilinnuke aka &amp;quot;Merka&amp;quot;&lt;/title&gt;
        ///&lt;author&gt;Nancy Snyder&lt;/author&gt;
        ///&lt;authorid&gt;naneki&lt;/authorid&gt;
        ///&lt;copyright&gt;(c) Copyright 2007 by Nancy Snyder&lt;/copyright&gt;
        ///&lt;id&gt;#1611 (v.1)&lt;/id&gt;
        ///&lt;description&gt;You are such a brave soul, I hope you enjoy this picture of you
        ///
        ///ps: couldn&amp;apos;t get your nose right (computer wouldn&amp;apos;t allow me to do it t [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string webpbn001611 {
            get {
                return ResourceManager.GetString("webpbn001611", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE pbn SYSTEM &quot;https://webpbn.com/pbn-0.3.dtd&quot;&gt;
        ///&lt;puzzleset&gt;
        ///&lt;source&gt;webpbn.com&lt;/source&gt;
        ///
        ///&lt;puzzle type=&quot;grid&quot; defaultcolor=&quot;black&quot;&gt;
        ///&lt;title&gt;Tragic Love Story&lt;/title&gt;
        ///&lt;author&gt;Nancy Snyder&lt;/author&gt;
        ///&lt;authorid&gt;naneki&lt;/authorid&gt;
        ///&lt;copyright&gt;(c) Copyright 2007 by Nancy Snyder&lt;/copyright&gt;
        ///&lt;id&gt;#1694 (v.1)&lt;/id&gt;
        ///&lt;description&gt;Brett &amp;amp; Scarlett
        ///&amp;quot;Gone with the Wind&amp;quot;&lt;/description&gt;
        ///&lt;note&gt;published,definitely unique,may require much guessing&lt;/note&gt;
        ///
        ///&lt;color name=&quot;white&quot; char=&quot;.&quot;&gt;FFFFF [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string webpbn001694 {
            get {
                return ResourceManager.GetString("webpbn001694", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE pbn SYSTEM &quot;https://webpbn.com/pbn-0.3.dtd&quot;&gt;
        ///&lt;puzzleset&gt;
        ///&lt;source&gt;webpbn.com&lt;/source&gt;
        ///
        ///&lt;puzzle type=&quot;grid&quot; defaultcolor=&quot;black&quot;&gt;
        ///&lt;title&gt;&amp;quot;I am not interested in money. I just want to be wonderful.&amp;quot;&lt;/title&gt;
        ///&lt;author&gt;Nancy Snyder&lt;/author&gt;
        ///&lt;authorid&gt;naneki&lt;/authorid&gt;
        ///&lt;copyright&gt;(c) Copyright 2007 by Nancy Snyder&lt;/copyright&gt;
        ///&lt;id&gt;#2040 (v.1)&lt;/id&gt;
        ///&lt;description&gt;Marilyn Monroe born Norma Jeane Mortenson June 1, 1926 &amp;#150; August 5, 1962
        ///
        ///I know she&amp;apos;s been done before,  [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string webpbn002040 {
            get {
                return ResourceManager.GetString("webpbn002040", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE pbn SYSTEM &quot;https://webpbn.com/pbn-0.3.dtd&quot;&gt;
        ///&lt;puzzleset&gt;
        ///&lt;source&gt;webpbn.com&lt;/source&gt;
        ///
        ///&lt;puzzle type=&quot;grid&quot; defaultcolor=&quot;black&quot;&gt;
        ///&lt;title&gt;Where there&amp;apos;s smoke...&lt;/title&gt;
        ///&lt;author&gt;Marcus&lt;/author&gt;
        ///&lt;authorid&gt;aanet&lt;/authorid&gt;
        ///&lt;copyright&gt;(c) Copyright 2008 by Marcus&lt;/copyright&gt;
        ///&lt;id&gt;#2413 (v.1)&lt;/id&gt;
        ///&lt;description&gt;Man with pipe and cap.&lt;/description&gt;
        ///&lt;note&gt;published,definitely unique,definitely requires moderate lookahead&lt;/note&gt;
        ///
        ///&lt;color name=&quot;white&quot; char=&quot;.&quot;&gt;FFFFFF&lt;/color&gt;
        ///&lt;color nam [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string webpbn002413 {
            get {
                return ResourceManager.GetString("webpbn002413", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE pbn SYSTEM &quot;https://webpbn.com/pbn-0.3.dtd&quot;&gt;
        ///&lt;puzzleset&gt;
        ///&lt;source&gt;webpbn.com&lt;/source&gt;
        ///
        ///&lt;puzzle type=&quot;grid&quot; defaultcolor=&quot;blue&quot;&gt;
        ///&lt;title&gt;who&amp;apos;s flag # 40&lt;/title&gt;
        ///&lt;author&gt;harris harris&lt;/author&gt;
        ///&lt;authorid&gt;torough4u&lt;/authorid&gt;
        ///&lt;copyright&gt;(c) Copyright 2008 by harris harris&lt;/copyright&gt;
        ///&lt;id&gt;#2556 (v.1)&lt;/id&gt;
        ///&lt;description&gt;Israel&lt;/description&gt;
        ///&lt;note&gt;published,definitely non-unique,definitely requires some guessing&lt;/note&gt;
        ///
        ///&lt;color name=&quot;white&quot; char=&quot;.&quot;&gt;FFFFFF&lt;/color&gt;
        ///&lt;color name=&quot;blue [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string webpbn002556 {
            get {
                return ResourceManager.GetString("webpbn002556", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE pbn SYSTEM &quot;https://webpbn.com/pbn-0.3.dtd&quot;&gt;
        ///&lt;puzzleset&gt;
        ///&lt;source&gt;webpbn.com&lt;/source&gt;
        ///
        ///&lt;puzzle type=&quot;grid&quot; defaultcolor=&quot;black&quot;&gt;
        ///&lt;title&gt;The Lion and the Stone&lt;/title&gt;
        ///&lt;author&gt;Marto Benwa&lt;/author&gt;
        ///&lt;authorid&gt;martobenwa&lt;/authorid&gt;
        ///&lt;copyright&gt;(c) Copyright 2008 by Marto Benwa&lt;/copyright&gt;
        ///&lt;id&gt;#2712 (v.1)&lt;/id&gt;
        ///&lt;description&gt;The most fantastic logo in the world&lt;/description&gt;
        ///&lt;note&gt;published,definitely non-unique,may require much guessing&lt;/note&gt;
        ///
        ///&lt;color name=&quot;white&quot; char=&quot;.&quot;&gt;FFFFFF&lt;/co [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string webpbn002712 {
            get {
                return ResourceManager.GetString("webpbn002712", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE pbn SYSTEM &quot;https://webpbn.com/pbn-0.3.dtd&quot;&gt;
        ///&lt;puzzleset&gt;
        ///&lt;source&gt;webpbn.com&lt;/source&gt;
        ///
        ///&lt;puzzle type=&quot;grid&quot; defaultcolor=&quot;black&quot;&gt;
        ///&lt;title&gt;I only speak &amp;quot;sign&amp;quot; language&lt;/title&gt;
        ///&lt;author&gt;Adam Nielson&lt;/author&gt;
        ///&lt;authorid&gt;monkeyboy&lt;/authorid&gt;
        ///&lt;copyright&gt;(c) Copyright 2008 by Adam Nielson&lt;/copyright&gt;
        ///&lt;id&gt;#3541 (v.1)&lt;/id&gt;
        ///&lt;description&gt;Wile. E. Coyote!  He only speaks by holding up a sign with whatever he wants us to see him &amp;quot;say.&amp;quot; (Thanks for the request, Sylvain)&lt;/de [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string webpbn003541 {
            get {
                return ResourceManager.GetString("webpbn003541", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE pbn SYSTEM &quot;https://webpbn.com/pbn-0.3.dtd&quot;&gt;
        ///&lt;puzzleset&gt;
        ///&lt;source&gt;webpbn.com&lt;/source&gt;
        ///
        ///&lt;puzzle type=&quot;grid&quot; defaultcolor=&quot;black&quot;&gt;
        ///&lt;title&gt;m&amp;amp;m (most satisfactory puzzle for some)&lt;/title&gt;
        ///&lt;author&gt;sanane samanye&lt;/author&gt;
        ///&lt;authorid&gt;maceraseven&lt;/authorid&gt;
        ///&lt;copyright&gt;(c) Copyright 2009 by sanane samanye&lt;/copyright&gt;
        ///&lt;id&gt;#4645 (v.1)&lt;/id&gt;
        ///&lt;description&gt;because some like it hot. say hello to marilyn monroe. &lt;/description&gt;
        ///&lt;note&gt;published,definitely unique,may require moderate lookahead [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string webpbn004645 {
            get {
                return ResourceManager.GetString("webpbn004645", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE pbn SYSTEM &quot;https://webpbn.com/pbn-0.3.dtd&quot;&gt;
        ///&lt;puzzleset&gt;
        ///&lt;source&gt;webpbn.com&lt;/source&gt;
        ///
        ///&lt;puzzle type=&quot;grid&quot; defaultcolor=&quot;black&quot;&gt;
        ///&lt;title&gt;Lasts Forever&lt;/title&gt;
        ///&lt;author&gt;Gator&lt;/author&gt;
        ///&lt;authorid&gt;gator&lt;/authorid&gt;
        ///&lt;copyright&gt;(c) Copyright 2009 by Gator&lt;/copyright&gt;
        ///&lt;id&gt;#6574 (v.1)&lt;/id&gt;
        ///&lt;description&gt;First Class Forever Stamp depicting the Liberty Bell.&lt;/description&gt;
        ///&lt;note&gt;published,definitely unique,definitely requires moderate lookahead&lt;/note&gt;
        ///
        ///&lt;color name=&quot;white&quot; char=&quot;.&quot;&gt;FFFFFF&lt;/co [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string webpbn006574 {
            get {
                return ResourceManager.GetString("webpbn006574", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE pbn SYSTEM &quot;https://webpbn.com/pbn-0.3.dtd&quot;&gt;
        ///&lt;puzzleset&gt;
        ///&lt;source&gt;webpbn.com&lt;/source&gt;
        ///
        ///&lt;puzzle type=&quot;grid&quot; defaultcolor=&quot;black&quot;&gt;
        ///&lt;title&gt;Pogo Karate&lt;/title&gt;
        ///&lt;author&gt;Mike Kam&lt;/author&gt;
        ///&lt;authorid&gt;ZL.oft&lt;/authorid&gt;
        ///&lt;copyright&gt;(c) Copyright 2009 by Mike Kam&lt;/copyright&gt;
        ///&lt;id&gt;#6739 (v.1)&lt;/id&gt;
        ///&lt;description&gt;err... Fight at night time?&lt;/description&gt;
        ///&lt;note&gt;published,definitely non-unique,may require much guessing&lt;/note&gt;
        ///
        ///&lt;color name=&quot;white&quot; char=&quot;.&quot;&gt;FFFFFF&lt;/color&gt;
        ///&lt;color name=&quot;black&quot; char= [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string webpbn006739 {
            get {
                return ResourceManager.GetString("webpbn006739", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE pbn SYSTEM &quot;https://webpbn.com/pbn-0.3.dtd&quot;&gt;
        ///&lt;puzzleset&gt;
        ///&lt;source&gt;webpbn.com&lt;/source&gt;
        ///
        ///&lt;puzzle type=&quot;grid&quot; defaultcolor=&quot;black&quot;&gt;
        ///&lt;title&gt;No DiCaprio, that&amp;apos;s for sure&lt;/title&gt;
        ///&lt;author&gt;Adam Nielson&lt;/author&gt;
        ///&lt;authorid&gt;monkeyboy&lt;/authorid&gt;
        ///&lt;copyright&gt;(c) Copyright 2010 by Adam Nielson&lt;/copyright&gt;
        ///&lt;id&gt;#7604 (v.1)&lt;/id&gt;
        ///&lt;description&gt;But he is a &amp;quot;leo,&amp;quot; nonetheless.  :-)
        ///This is just a cool lion mascot logo.  &lt;/description&gt;
        ///&lt;note&gt;published,definitely unique,definitely lin [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string webpbn007604 {
            get {
                return ResourceManager.GetString("webpbn007604", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE pbn SYSTEM &quot;https://webpbn.com/pbn-0.3.dtd&quot;&gt;
        ///&lt;puzzleset&gt;
        ///&lt;source&gt;webpbn.com&lt;/source&gt;
        ///
        ///&lt;puzzle type=&quot;grid&quot; defaultcolor=&quot;black&quot;&gt;
        ///&lt;title&gt;Domino Logic III (Abstract pattern)&lt;/title&gt;
        ///&lt;author&gt;Josh Greifer&lt;/author&gt;
        ///&lt;authorid&gt;joshgreifer&lt;/authorid&gt;
        ///&lt;copyright&gt;(c) Copyright 2010 by Josh Greifer&lt;/copyright&gt;
        ///&lt;id&gt;#8098 (v.1)&lt;/id&gt;
        ///&lt;description&gt;&lt;/description&gt;
        ///&lt;note&gt;published,definitely unique,definitely requires moderate lookahead&lt;/note&gt;
        ///
        ///&lt;color name=&quot;white&quot; char=&quot;.&quot;&gt;FFFFFF&lt;/color&gt;
        ///&lt;color [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string webpbn008098 {
            get {
                return ResourceManager.GetString("webpbn008098", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE pbn SYSTEM &quot;https://webpbn.com/pbn-0.3.dtd&quot;&gt;
        ///&lt;puzzleset&gt;
        ///&lt;source&gt;webpbn.com&lt;/source&gt;
        ///
        ///&lt;puzzle type=&quot;grid&quot; defaultcolor=&quot;black&quot;&gt;
        ///&lt;title&gt;Sacred Lithuanian nature&lt;/title&gt;
        ///&lt;author&gt;asta paka&lt;/author&gt;
        ///&lt;authorid&gt;asta-paka&lt;/authorid&gt;
        ///&lt;copyright&gt;(c) Copyright 2010 by asta paka&lt;/copyright&gt;
        ///&lt;id&gt;#9892 (v.1)&lt;/id&gt;
        ///&lt;description&gt;&lt;/description&gt;
        ///&lt;note&gt;published,definitely non-unique,may require much guessing&lt;/note&gt;
        ///
        ///&lt;color name=&quot;white&quot; char=&quot;.&quot;&gt;FFFFFF&lt;/color&gt;
        ///&lt;color name=&quot;black&quot; char=&quot;X&quot;&gt;00000 [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string webpbn009892 {
            get {
                return ResourceManager.GetString("webpbn009892", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE pbn SYSTEM &quot;https://webpbn.com/pbn-0.3.dtd&quot;&gt;
        ///&lt;puzzleset&gt;
        ///&lt;source&gt;webpbn.com&lt;/source&gt;
        ///
        ///&lt;puzzle type=&quot;grid&quot; defaultcolor=&quot;black&quot;&gt;
        ///&lt;title&gt;Buffalo Solider&lt;/title&gt;
        ///&lt;author&gt;Shelly Havok&lt;/author&gt;
        ///&lt;authorid&gt;HavoksAngel.1&lt;/authorid&gt;
        ///&lt;copyright&gt;(c) Copyright 2010 by Shelly Havok&lt;/copyright&gt;
        ///&lt;id&gt;#10088 (v.1)&lt;/id&gt;
        ///&lt;description&gt;&lt;/description&gt;
        ///&lt;note&gt;published,definitely non-unique,may require much guessing&lt;/note&gt;
        ///
        ///&lt;color name=&quot;white&quot; char=&quot;.&quot;&gt;FFFFFF&lt;/color&gt;
        ///&lt;color name=&quot;black&quot; char=&quot;X&quot;&gt;000 [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string webpbn010088 {
            get {
                return ResourceManager.GetString("webpbn010088", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE pbn SYSTEM &quot;https://webpbn.com/pbn-0.3.dtd&quot;&gt;
        ///&lt;puzzleset&gt;
        ///&lt;source&gt;webpbn.com&lt;/source&gt;
        ///
        ///&lt;puzzle type=&quot;grid&quot; defaultcolor=&quot;black&quot;&gt;
        ///&lt;title&gt;Centerpiece&lt;/title&gt;
        ///&lt;author&gt;Bo Na&lt;/author&gt;
        ///&lt;authorid&gt;korean&lt;/authorid&gt;
        ///&lt;copyright&gt;(c) Copyright 2010 by Bo Na&lt;/copyright&gt;
        ///&lt;id&gt;#10810 (v.1)&lt;/id&gt;
        ///&lt;description&gt;&lt;/description&gt;
        ///&lt;note&gt;published,definitely non-unique,may require much guessing&lt;/note&gt;
        ///
        ///&lt;color name=&quot;white&quot; char=&quot;.&quot;&gt;FFFFFF&lt;/color&gt;
        ///&lt;color name=&quot;black&quot; char=&quot;X&quot;&gt;000000&lt;/color&gt;
        ///
        ///&lt;clues type= [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string webpbn010810 {
            get {
                return ResourceManager.GetString("webpbn010810", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE pbn SYSTEM &quot;https://webpbn.com/pbn-0.3.dtd&quot;&gt;
        ///&lt;puzzleset&gt;
        ///&lt;source&gt;webpbn.com&lt;/source&gt;
        ///
        ///&lt;puzzle type=&quot;grid&quot; defaultcolor=&quot;black&quot;&gt;
        ///&lt;title&gt;Fractal Iteration #5&lt;/title&gt;
        ///&lt;author&gt;Joshua Nolan&lt;/author&gt;
        ///&lt;authorid&gt;the jew&lt;/authorid&gt;
        ///&lt;copyright&gt;(c) Copyright 2011 by Joshua Nolan&lt;/copyright&gt;
        ///&lt;id&gt;#12548 (v.1)&lt;/id&gt;
        ///&lt;description&gt;This is the (almost certainly) final iteration of the sierpinski triangle iterations.  You have to use the others to solve it!!!&lt;/description&gt;
        ///&lt;note&gt;published,defin [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string webpbn012548 {
            get {
                return ResourceManager.GetString("webpbn012548", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE pbn SYSTEM &quot;https://webpbn.com/pbn-0.3.dtd&quot;&gt;
        ///&lt;puzzleset&gt;
        ///&lt;source&gt;webpbn.com&lt;/source&gt;
        ///
        ///&lt;puzzle type=&quot;grid&quot; defaultcolor=&quot;black&quot;&gt;
        ///&lt;title&gt;Its cold...&lt;/title&gt;
        ///&lt;author&gt;Juliane&lt;/author&gt;
        ///&lt;authorid&gt;Ju1985&lt;/authorid&gt;
        ///&lt;copyright&gt;(c) Copyright 2012 by Juliane&lt;/copyright&gt;
        ///&lt;id&gt;#18297 (v.1)&lt;/id&gt;
        ///&lt;description&gt;...an ice-cold hand (Thing T. Thing)
        ///
        ///In german it&amp;apos;s called &amp;quot;Eiskaltes H&amp;#228;ndchen&amp;quot; ;)&lt;/description&gt;
        ///&lt;note&gt;published,definitely non-unique,may require much guessing&lt; [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string webpbn018297 {
            get {
                return ResourceManager.GetString("webpbn018297", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE pbn SYSTEM &quot;https://webpbn.com/pbn-0.3.dtd&quot;&gt;
        ///&lt;puzzleset&gt;
        ///&lt;source&gt;webpbn.com&lt;/source&gt;
        ///
        ///&lt;puzzle type=&quot;grid&quot; defaultcolor=&quot;black&quot;&gt;
        ///&lt;title&gt;November 19,1863&lt;/title&gt;
        ///&lt;author&gt;Byron Walter&lt;/author&gt;
        ///&lt;authorid&gt;papa&lt;/authorid&gt;
        ///&lt;copyright&gt;(c) Copyright 2013 by Byron Walter&lt;/copyright&gt;
        ///&lt;id&gt;#22336 (v.1)&lt;/id&gt;
        ///&lt;description&gt;&lt;/description&gt;
        ///&lt;note&gt;published,definitely non-unique,may require much guessing&lt;/note&gt;
        ///
        ///&lt;color name=&quot;white&quot; char=&quot;.&quot;&gt;FFFFFF&lt;/color&gt;
        ///&lt;color name=&quot;black&quot; char=&quot;X&quot;&gt;000000&lt;/col [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string webpbn022336 {
            get {
                return ResourceManager.GetString("webpbn022336", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE pbn SYSTEM &quot;https://webpbn.com/pbn-0.3.dtd&quot;&gt;
        ///&lt;puzzleset&gt;
        ///&lt;source&gt;webpbn.com&lt;/source&gt;
        ///
        ///&lt;puzzle type=&quot;grid&quot; defaultcolor=&quot;black&quot;&gt;
        ///&lt;title&gt;diagonal bricks&lt;/title&gt;
        ///&lt;author&gt;ssss&lt;/author&gt;
        ///&lt;authorid&gt;ssss&lt;/authorid&gt;
        ///&lt;copyright&gt;(c) Copyright 2017 by ssss&lt;/copyright&gt;
        ///&lt;id&gt;#30110 (v.1)&lt;/id&gt;
        ///&lt;description&gt;&lt;/description&gt;
        ///&lt;note&gt;published,definitely non-unique,definitely requires some guessing&lt;/note&gt;
        ///
        ///&lt;color name=&quot;white&quot; char=&quot;.&quot;&gt;FFFFFF&lt;/color&gt;
        ///&lt;color name=&quot;black&quot; char=&quot;X&quot;&gt;000000&lt;/color&gt;
        ///
        ///&lt;clu [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string webpbn030110 {
            get {
                return ResourceManager.GetString("webpbn030110", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE pbn SYSTEM &quot;https://webpbn.com/pbn-0.3.dtd&quot;&gt;
        ///&lt;puzzleset&gt;
        ///&lt;source&gt;webpbn.com&lt;/source&gt;
        ///
        ///&lt;puzzle type=&quot;grid&quot; defaultcolor=&quot;black&quot;&gt;
        ///&lt;title&gt;Mmmmm!!!&lt;/title&gt;
        ///&lt;author&gt;Michel Plourde&lt;/author&gt;
        ///&lt;authorid&gt;micplour&lt;/authorid&gt;
        ///&lt;copyright&gt;(c) Copyright 2020 by Michel Plourde&lt;/copyright&gt;
        ///&lt;id&gt;#34024 (v.1)&lt;/id&gt;
        ///&lt;description&gt;Qui a croqu&amp;#195;&amp;#169; dans ma pomme?&lt;/description&gt;
        ///&lt;note&gt;published,definitely unique,definitely line/color solvable&lt;/note&gt;
        ///
        ///&lt;color name=&quot;white&quot; char=&quot;.&quot;&gt;FFFFFF&lt;/color&gt;
        ///&lt; [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string webpbn034024 {
            get {
                return ResourceManager.GetString("webpbn034024", resourceCulture);
            }
        }
    }
}
